#COMPILE EXE
#DIM ALL

FUNCTION PBMAIN () AS LONG

  LOCAL hWin AS DWORD
  LOCAL widthvar AS INTEGER
  LOCAL Heightvar AS INTEGER
  LOCAL inkeyvar AS STRING
  LOCAL NumericVar AS LONG

  GRAPHIC WINDOW "Atco MCU Test",400, 400,600, 400 TO hWin
  GRAPHIC ATTACH hWin, 0
  GRAPHIC BOX (10, 10) - (120, 120), 0, %BLUE
  GRAPHIC PRINT "Hello" POS(1)
  GRAPHIC SET POS [STEP] (50, 10)
  DO WHILE 1
    GRAPHIC INSTAT TO NumericVar
    IF (NumericVar) THEN
        GRAPHIC INKEY$ TO inkeyVar$
        GRAPHIC PRINT inkeyVar$ POS(50)
    END IF

  LOOP



END FUNCTION
