GLOBAL Pi AS DOUBLE
GLOBAL TXT AS STRING
GLOBAL a,b, DelH, DelV, s, s1 AS DOUBLE
GLOBAL i, j, n1, n2, n3,  kmax,sel AS LONG
GLOBAL x,x1,y,y1 AS DOUBLE
GLOBAL demo AS LONG
GLOBAL usecolor AS LONG
GLOBAL kbd AS STRING
GLOBAL AE, AO, ED, OE, AB, area, AOE AS DOUBLE
GLOBAL centerx, centery AS LONG
GLOBAL radius AS LONG
GLOBAL central_angle, arc_ABD, arc_ABR, arclen_AB AS DOUBLE
GLOBAL circumference,chord_AB, circle_area AS DOUBLE
GLOBAL Sector_area AS DOUBLE
GLOBAL Triangle_Area, Segment_area AS DOUBLE       