#COMPILE EXE
#INCLUDE "WIN32API.INC"

%ParentWidth  = 1000
%ParentHeight = 1000
%ParentX      = 0
%ParentY      = 0

GLOBAL hParent AS LONG

CALLBACK FUNCTION ParentProc AS LONG
    SELECT CASE CB.MSG
        CASE %WM_KEYDOWN
          MSGBOX "%WM_KEYDOWN " + HEX$(CB.WPARAM)
          FUNCTION = 0
    END SELECT
END FUNCTION


FUNCTION PBMAIN
  DIALOG NEW PIXELS, 0, "Graphic Child Window",%ParentX,%ParentY,%ParentWidth,%ParentHeight,%WS_SYSMENU OR %WS_CAPTION OR %WS_MINIMIZEBOX TO hParent
  LOCAL ROW AS LONG
  LOCAL i AS LONG



  DIALOG SHOW MODELESS hParent, CALL ParentProc
  DO
    DIALOG GET SIZE hParent TO x&, x&
    DIALOG DOEVENTS 0
  LOOP WHILE x&
END FUNCTION
