' *************************************************************************************
'                    Code Generated by EZGUI Professional Visual Designer 5.0
'           Portions: Copyright Christopher R. Boss, 2003 to 2011 All Rights Reserved !
'              Registered EZGUI 5.0 users may use generated code Royalty Free !
' *************************************************************************************
'
' -----------------------------------------------------------------------------------------
'            WARNING !    Do Not Modify any code WITHIN Protected Sections !
' You can add code (Sub,Function,etc.) BEFORE any Protected Routine by using the following
' CODE TAGS:        '<<SAVE>>      '<<END>>            and the Designer will not remove it.
' -----------------------------------------------------------------------------------------
'

' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================


'
#COMPILE EXE
#DIM ALL        '   This is helpful to prevent errors in coding
' --------------------
#INCLUDE "C:\ezgui50pro\includes\ezgui50.inc"                          ' EZGUI Include file for Declares
' --------------------
' *************************************************************************************


' *************************************************************************************
'                   Code Generator Defined Constants and Declares
' *************************************************************************************
DECLARE FUNCTION Main_Initialize(BYVAL VerNum&) AS LONG
DECLARE SUB OtherForm_Events(FormName$, CID&, CMsg&, CVal&, Cancel&)
DECLARE SUB OtherForm_Design(FormName$)
DECLARE FUNCTION PreProcess_Events(FormName$, CID&, CMsg&, CVal&, Cancel&) AS LONG
DECLARE SUB EZ_FORM1_Display(BYVAL FParent$)
DECLARE SUB EZ_FORM1_Design()
DECLARE SUB EZ_FORM1_ParseEvents(CID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FORM1_Events(CID&, CMsg&, CVal&, Cancel&)
' ------------------------------------------------


' ----------------------------------------------------------
%FORM1_FILE                                   = 9000
' ----------------------------------------------------------
%FORM1_OPEN                                   = 9005
%FORM1_SAVE                                   = 9010
%FORM1_LISTBOX1           = 100

DECLARE SUB FORM1_LISTBOX1_Events(MyID&, CMsg&, CVal&, Cancel&)



' *************************************************************************************
'                 Code Generator Defined Global Variables and Types
' *************************************************************************************



'    Note:     Do NOT change the names of the EZGUI Callback Procedures !

' --------------------
#INCLUDE "C:\ezgui50pro\includes\ezwmain50.inc"                          ' EZGUI Include file for WinMain
' --------------------



' *************************************************************************************
'                       User Defined Global Variables and Types
'         (Put code in CODE TAGS! to protect from deletion by Code Generator !)
' *************************************************************************************

SUB EZ_Main(VerNum&)     ' (PROTECTED)
     EZ_Reg %EZ_CUSTID,%EZ_REGNUM
     EZ_DefImageFolder "Graphics"
     EZ_AllowCommandEvents  0
     EZ_DefFont 6, "Arial", 10, "V"
     EZ_DefFont 7, "Courier New", 10, "F"
     EZ_DefFont 8, "Times New Roman", 10, "V"
     EZ_DefFont 9, "Modern", 10, "V"
     EZ_DefSystemColor 32, 4
     EZ_DefSystemColor 33, 5
     EZ_DefSystemColor 34, 15
     EZ_DefSystemColor 35, 24
     EZ_DefColorL 36, &H00B96FFF
     EZ_DefColorL 37, &H0014AB9F
     EZ_DefColorL 38, &H0047A7FF
     EZ_DefColorL 39, &H00D2AACF
     EZ_DefColorL 40, &H001CD5E3
     EZ_DefColorL 41, &H00BC8943
     EZ_DefColorL 42, &H006C6AB7
     EZ_DefColorL 43, &H00DD4489
     IF Main_Initialize(VerNum&) THEN
          EZ_FORM1_Display ""
     END IF
END SUB

' -------------------------------------------------------------------------------------

SUB EZ_DesignWindow(FormName$)     ' (PROTECTED)
     SELECT CASE FormName$
          CASE "FORM1"
               EZ_FORM1_Design
          CASE ELSE
               OtherForm_Design FormName$
     END SELECT
END SUB

' -------------------------------------------------------------------------------------

SUB EZ_Events(FormName$, CID&, CMsg&, CVal&, Cancel&)     ' (PROTECTED)
     IF PreProcess_Events(FormName$, CID&, CMsg&, CVal&, Cancel&) THEN EXIT SUB
     SELECT CASE FormName$
          CASE "FORM1"
               EZ_FORM1_ParseEvents CID&, CMsg&, CVal&, Cancel&
          CASE ELSE
               OtherForm_Events FormName$, CID&, CMsg&, CVal&, Cancel&
     END SELECT
END SUB

' -------------------------------------------------------------------------------------






' *************************************************************************************
'                                Applications FORM Code
' *************************************************************************************


' ======================================
' [USER ACCESSABLE CODE]  You may Edit !
' ======================================
TYPE TestRecord
   header AS STRING  * 20
   NumModules AS INTEGER
   StatusDef AS LONG
   MyArray(10) AS SINGLE
   MyMulti(10,10) AS DOUBLE
END TYPE
GLOBAL filename AS STRING
GLOBAL TestStruc AS TestRecord
DECLARE SUB DFRead (filenum AS INTEGER, passrec AS TestRecord , OFFSET AS INTEGER)
DECLARE SUB DFWrite (filenum AS INTEGER, passrec AS TestRecord , OFFSET AS INTEGER)
DECLARE SUB FCreate (filenumber AS INTEGER, myattr AS INTEGER, filename AS STRING)
DECLARE SUB FOpen (FileNumber AS INTEGER, ReadWrite AS INTEGER, Sharing AS INTEGER, filename AS STRING)

FUNCTION Main_Initialize(BYVAL VerNum&) AS LONG
     LOCAL RV&
     RV&=1
     FUNCTION=RV&
     LOCAL I,J AS INTEGER
     LOCAL filename AS STRING
     filename = "Test.cal"
     FOR I%=0 TO 10
         TestStruc.MyArray(I%) = I%
     NEXT I%
     FOR I%=0 TO 10
          FOR J%=0 TO 10
              TestStruc.MyMulti(I,J) = J%
          NEXT J%
     NEXT I%
     TestStruc.header = "Atco Cal file"
     TestStruc.NumModules = 3
     TestStruc.StatusDef = 10
END FUNCTION

SUB OtherForm_Design(FormName$)
     SELECT CASE FormName$
          CASE ELSE
     END SELECT
END SUB

SUB OtherForm_Events(FormName$, CID&, CMsg&, CVal&, Cancel&)
     SELECT CASE FormName$
          CASE "{OPENDLG}", "{SAVEDLG}", "{OPENDLGX}", "{SAVEDLGX}", "{COLORDLG}", "{FONTDLG}", "{PRINTDLG}", "{PAGEDLG}", "{FINDDLG}"
          CASE "{ABORTDLG}"
          CASE "{MSGBOX}"
          CASE "{APP}"      ' Not a Form
               SELECT CASE CMsg&
                    CASE %EZ_NoTheme
                    CASE %EZ_Terminate
               END SELECT
          CASE ELSE
     END SELECT
END SUB

FUNCTION PreProcess_Events(FormName$, CID&, CMsg&, CVal&, Cancel&) AS LONG
     LOCAL RV&
     RV&=0
     FUNCTION=RV&
END FUNCTION


'<<BEGINFORM>> "FORM1"


' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================

SUB EZ_FORM1_Display(BYVAL FParent$)     ' (PROTECTED)
     LOCAL hMainMenu&
     ' Main Menu handle automatically stored by EZGUI
     hMainMenu&=EZ_DefMainMenu( %FORM1_FILE, "&File", "")
     EZ_Color -1, -1
     EZ_Form "FORM1", FParent$, "Test IO", 0, 0, 80, 30, "C"
END SUB

SUB EZ_FORM1_Design()     ' (PROTECTED)
     LOCAL CText$
     LOCAL hMainMenu&, hDropMenu&, hSubMenu&
     hMainMenu&=EZ_GetMenu("FORM1", 0)
     hDropMenu&=EZ_DefSubMenu( %FORM1_OPEN, "&Load", "")
     EZ_SaveMenu "FORM1", 1, hDropMenu&
     EZ_SetSubMenu hMainMenu& , %FORM1_FILE, hDropMenu&
     EZ_AddMenuItem hDropMenu&, %FORM1_SAVE, 0, "&Save", ""
     ' ------------------------------------------------

     EZ_Color-1,-1
     EZ_UseFont 4
     EZ_ListBox %FORM1_LISTBOX1, 13, 3, 50, 6, "", "ASTV"
     ' -----------------------------------------------
END SUB


' ======================================
' [USER ACCESSABLE CODE]  You may Edit !
' ======================================

SUB FORM1_MenuEvents(BYVAL MyID&, CMsg&, CVal&, Cancel&, BYVAL hMenu&, BYVAL MenuText$)
     LOCAL L AS STRING
     LOCAL LIST AS STRING
     SELECT CASE MyID&
          CASE %FORM1_FILE
               SELECT CASE CMsg&
                    CASE %EZ_Click
                    CASE %EZ_Selected
               END SELECT
          CASE %FORM1_OPEN
               SELECT CASE CMsg&
                    CASE %EZ_Click
                         CalLoad(filename)
                         list = STR$(TestStruc.MyMulti(5,5))+"|"+TestStruc.header+"|"+STR$(TestStruc.MyArray(4))

                         EZ_AddItems "FORM1", %FORM1_LISTBOX1, LIST$
                    CASE %EZ_Selected
               END SELECT
          CASE %FORM1_SAVE
               SELECT CASE CMsg&
                    CASE %EZ_Click
                         CalSave(filename)
                    CASE %EZ_Selected
               END SELECT
          CASE ELSE
     END SELECT
END SUB
FUNCTION CalSave(filename AS STRING) AS INTEGER
    LOCAL filenumber AS INTEGER
    LOCAL F AS STRING
    F$ = EZ_SaveFile("FORM1","Save your file", "", _
                      "mycalfile.cal", _
                      "Cal*.cal|All Files|*.*|", _
                      "cal", "PNS")

    FCreate (filenumber, 0, F$)
    CALL DFWrite(filenumber, BYVAL VARPTR(TestStruc), 0)
    CALL FClose(filenumber)
END FUNCTION

FUNCTION CalLoad(filename AS STRING) AS INTEGER
   LOCAL filenumber AS INTEGER
   LOCAL F AS STRING
   F$=EZ_OpenFile("FORM1","Select any file you want:","",_
               "Cal (*.cal))|*.cal|All Files (*.*)|*.*|",_
               "PRZ")

   CALL FOpen (filenumber, 0,0, filename)
   CALL DFRead(filenumber, BYVAL VARPTR(TestStruc),0)
END FUNCTION

SUB DFRead (filenum AS INTEGER, passrec AS TestRecord , OFFSET AS INTEGER)
    GET filenum, offset ,PASSREC
END SUB

SUB DFWrite (filenum AS INTEGER, passrec AS TestRecord , OFFSET AS INTEGER)
        PUT filenum,  offset ,PASSREC
END SUB

SUB FCreate (filenumber AS INTEGER, ATTR AS INTEGER, filename AS STRING)
    LOCAL FileExists AS INTEGER
    FileExists = ISFILE(FileName)
    IF FileExists THEN
        OPEN filename FOR BINARY AS filenumber BASE = 0
    ELSE
        OPEN filename FOR BINARY AS filenumber BASE = 0
    END IF
END SUB

SUB FOpen (FileNumber AS INTEGER, ReadWrite AS INTEGER, Sharing AS INTEGER, filename AS STRING)
    LOCAL FileExists AS INTEGER
    FileExists = ISFILE(FileName)
    IF FileExists THEN
        OPEN filename FOR BINARY AS filenumber BASE = 0
    END IF
END SUB

SUB FClose (filenumber AS INTEGER)
    CLOSE filenumber
END SUB


' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================


SUB EZ_FORM1_ParseEvents(CID&, CMsg&, CVal&, Cancel&)     ' (PROTECTED)
     SELECT CASE CID&
          CASE %EZ_Window
               FORM1_Events CID&, CMsg&, CVal&, Cancel&
          CASE %FORM1_FILE
               FORM1_MenuEvents CID&, CMsg&, CVal&, Cancel&, EZ_GetMenu("FORM1", 0), "&File"
          CASE %FORM1_OPEN
               FORM1_MenuEvents CID&, CMsg&, CVal&, Cancel&, EZ_GetMenu("FORM1", 1), "&Load"
          CASE %FORM1_SAVE
               FORM1_MenuEvents CID&, CMsg&, CVal&, Cancel&, EZ_GetMenu("FORM1", 1), "&Save"
          CASE  %FORM1_LISTBOX1
               FORM1_LISTBOX1_Events CID&, CMsg&, CVal&, Cancel&
          CASE ELSE
               FORM1_Events CID&, CMsg&, CVal&, Cancel&
     END SELECT
END SUB

' ======================================
' [USER ACCESSABLE CODE]  You may Edit !
' ======================================

SUB FORM1_Events(CID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CID&
          CASE %EZ_Window
               SELECT CASE CMsg&
                    CASE %EZ_Loading
                    CASE %EZ_Loaded
                    CASE %EZ_Started
                    CASE %EZ_Close
                    CASE ELSE
               END SELECT
          CASE ELSE
     END SELECT
END SUB

SUB FORM1_LISTBOX1_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Change
          CASE ELSE
     END SELECT
END SUB
