' *************************************************************************************
'                    Code Generated by EZGUI Professional Visual Designer 5.0
'           Portions: Copyright Christopher R. Boss, 2003 to 2011 All Rights Reserved !
'              Registered EZGUI 5.0 users may use generated code Royalty Free !
' *************************************************************************************
'
' -----------------------------------------------------------------------------------------
'            WARNING !    Do Not Modify any code WITHIN Protected Sections !
' You can add code (Sub,Function,etc.) BEFORE any Protected Routine by using the following 
' CODE TAGS:        '<<SAVE>>      '<<END>>            and the Designer will not remove it.
' -----------------------------------------------------------------------------------------
'

' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================

DECLARE SUB EZ_JOYFORM_Display(BYVAL FParent$)
DECLARE SUB EZ_JOYFORM_Design()
DECLARE SUB EZ_JOYFORM_ParseEvents(CID&, CMsg&, CVal&, Cancel&)
DECLARE SUB JOYFORM_Events(CID&, CMsg&, CVal&, Cancel&)
' ------------------------------------------------

' -------------------------------
%JOYFORM_Timer_ID         = 3
' -------------------------------
DECLARE SUB JOYFORM_TimerEvents(BYVAL FormName$, BYVAL CID&, BYVAL CMsg&, CVal&, Cancel&)

%JOYFORM_XPOSLAB            = 100
%JOYFORM_YPOSLAB1           = 105
%JOYFORM_APOSLAB1           = 110
%JOYFORM_ZPOSLAB1           = 115
%JOYFORM_YPOSUPD            = 120
%JOYFORM_XPOSUPD            = 125
%JOYFORM_APOSUPD            = 130
%JOYFORM_ZPOSUPD            = 135
%JOYFORM_STOPBTN            = 140

DECLARE SUB JOYFORM_STOPBTN_Events(MyID&, CMsg&, CVal&, Cancel&)

'<<BEGINFORM>> "JOYFORM"


' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================

SUB EZ_JOYFORM_Display(BYVAL FParent$)     ' (PROTECTED)
     EZ_Color -1, -1
     EZ_AllowLoadingEvent 2
     EZ_Form "JOYFORM", FParent$, "Joy Stick", 0, 0, 90, 37, "CZ"
END SUB

SUB EZ_JOYFORM_Design()     ' (PROTECTED)
     LOCAL CText$
     EZ_Color 0, 14
     EZ_UseFont 4
     EZ_AllowLoadingEvent 2
     EZ_UseAutoSize "VH"
     EZ_Label %JOYFORM_XPOSLAB, 20, 5, 18, 1, "X POS", "C"
     ' -----------------------------------------------
     EZ_Color 0, 14
     EZ_UseFont 4
     EZ_AllowLoadingEvent 2
     EZ_UseAutoSize "VH"
     EZ_Label %JOYFORM_YPOSLAB1, 20, 7, 18, 1, "Y POS", "C"
     ' -----------------------------------------------
     EZ_Color 0, 14
     EZ_UseFont 4
     EZ_AllowLoadingEvent 2
     EZ_UseAutoSize "VH"
     EZ_Label %JOYFORM_APOSLAB1, 20, 9, 18, 1, "A POS", "C"
     ' -----------------------------------------------
     EZ_Color 0, 14
     EZ_UseFont 4
     EZ_AllowLoadingEvent 2
     EZ_UseAutoSize "VH"
     EZ_Label %JOYFORM_ZPOSLAB1, 20, 11, 18, 1, "Z POS", "C"
     ' -----------------------------------------------
     EZ_Color 0, 11
     EZ_UseFont 4
     EZ_UseAutoSize "VH"
     EZ_Label %JOYFORM_YPOSUPD, 40, 7, 13, 1, "", "C"
     ' -----------------------------------------------
     EZ_Color 0, 11
     EZ_UseFont 4
     EZ_Label %JOYFORM_XPOSUPD, 40, 5, 13, 1, "", "C"
     ' -----------------------------------------------
     EZ_Color 0, 11
     EZ_UseFont 4
     EZ_UseAutoSize "VH"
     EZ_Label %JOYFORM_APOSUPD, 40, 9, 13, 1, "", "C"
     ' -----------------------------------------------
     EZ_Color 0, 11
     EZ_UseFont 4
     EZ_UseAutoSize "VH"
     EZ_Label %JOYFORM_ZPOSUPD, 40, 11, 13, 1, "", "C"
     ' -----------------------------------------------
     EZ_Color 9, 15
     EZ_UseFont 4
     EZ_UseAutoSize "VH"
     EZ_SubClass 2
     EZ_ODButton %JOYFORM_STOPBTN, 21, 14, 33, 2, "Stop Joy Stick", "T"
     EZ_SubClass 0
     ' -----------------------------------------------
END SUB


SUB EZ_JOYFORM_ParseEvents(CID&, CMsg&, CVal&, Cancel&)     ' (PROTECTED)
     SELECT CASE CID&
          CASE %EZ_Window
               JOYFORM_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_Started OR CMsg&=%EZ_Close THEN
                    JOYFORM_TimerEvents "JOYFORM", %JOYFORM_Timer_ID, CMsg&, CVal&, Cancel&
               END IF
          CASE %JOYFORM_Timer_ID
               JOYFORM_TimerEvents "JOYFORM", CID&, CMsg&, CVal&, Cancel&
          CASE  %JOYFORM_STOPBTN
               JOYFORM_STOPBTN_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButton "JOYFORM", %JOYFORM_STOPBTN, CVal&, 15, 9,  4
               END IF
          CASE ELSE
               JOYFORM_Events CID&, CMsg&, CVal&, Cancel&
     END SELECT
END SUB

' ======================================
' [USER ACCESSABLE CODE]  You may Edit !
' ======================================

SUB JOYFORM_Events(CID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CID&
          CASE %EZ_Window
               SELECT CASE CMsg&
                    CASE %EZ_Loading
                    CASE %EZ_Loaded
                    CASE %EZ_Started
                    CASE %EZ_Close
                    CASE ELSE
               END SELECT
          CASE ELSE
     END SELECT
END SUB

'  Put other Subs above this one !

SUB JOYFORM_TimerEvents(BYVAL FormName$, BYVAL CID&, BYVAL CMsg&, CVal&, Cancel&)
     LOCAL TM!
     SELECT CASE CMsg&
          CASE %EZ_Timer          ' Timer Event !
          CASE %EZ_Started        ' Start Timer !
               TM!=10.0            ' Timer delay in seconds
               EZ_StartTimer FormName$, CID&, TM!
          CASE %EZ_Close          ' Terminate Timer when form closes !
               EZ_StopTimer FormName$, CID&
          CASE ELSE
     END SELECT
END SUB
SUB JOYFORM_STOPBTN_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE %EZ_LButtonDown
          CASE ELSE
     END SELECT
END SUB


