' *************************************************************************************
'                       Code Generated by EZGUI Visual Designer 4.5 Beta
'                       Portions: Copyright Christopher R. Boss, 2003 to 2009
'                                    All Rights Reserved !
'                 Registered EZGUI 4.5 users may use this code Royalty Free !
' *************************************************************************************
'
' --------------------------------------------------------
' WARNING ! Do Not Modify any code WITHIN Protected Sections !
' You can add code (Sub,Function,etc.) BEFORE any Protected Routine
' by using the following CODE TAGS:        '<<SAVE>>      '<<END>>
' and the Designer will not remove it.
' --------------------------------------------------------
'

' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================

DECLARE SUB EZ_PGSCROLLER_InitComponent(BYVAL CMPPrefix$)
DECLARE SUB EZ_PGSCROLLER_Design()
DECLARE SUB EZ_PGSCROLLER_ParseEvents(CID&, CMsg&, CVal&, Cancel&)
DECLARE SUB PGSCROLLER_Events(CID&, CMsg&, CVal&, Cancel&)
' ------------------------------------------------



'<<BEGINFORM>> "PGSCROLLER"


' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================

SUB EZ_PGSCROLLER_InitComponent(BYVAL CMPPrefix$)     ' (PROTECTED)
     EZ_DefComponent CMPPrefix$+"PGSCROLLER", "SVBK||PGSCROLLER.bas", CODEPTR(EZ_PGSCROLLER_Design), CODEPTR(EZ_PGSCROLLER_ParseEvents)
END SUB

SUB EZ_PGSCROLLER_Design()     ' (PROTECTED)
     LOCAL CText$
END SUB


SUB EZ_PGSCROLLER_ParseEvents(CID&, CMsg&, CVal&, Cancel&)     ' (PROTECTED)
     SELECT CASE CID&
          CASE %EZ_Window
               PGSCROLLER_Events CID&, CMsg&, CVal&, Cancel&
          CASE ELSE
               PGSCROLLER_Events CID&, CMsg&, CVal&, Cancel&
     END SELECT
END SUB

' ======================================
' [USER ACCESSABLE CODE]  You may Edit !
' ======================================

'<<SAVE>>
SUB CS_ShowForm(BYVAL F$)
     LOCAL W&, H&, CW&, CH&, FW!, FH!, SW&, SH&, SF$, X&, Y&, XDif&, YDif&, VScroll&, HScroll&, EW&, EH&
     LOCAL OKFlag&, AW!, AH!
     ' assume child form is hidden to begin with
'     EZ_HideC "{ME}",%CSCROLLER_MYPICTURE,%CSCROLLER_MYPICTURE
     IF F$="" THEN
          EZ_HideFormScrollBars "{ME}", "B"
          EXIT SUB
     END IF
     IF EZ_IsForm(F$, "Page")=0 THEN EXIT SUB
     IF EZ_GetME=EZ_GetFormParent(F$) THEN OKFlag&=1 ELSE OKFlag&=0
     IF OKFlag& THEN
          IF EZ_IsForm(F$,"V") THEN EZ_HideForm F$
          EZ_GetSize F$, AW!, AH!,1
          W&=AW!
          H&=AH!
          EZ_HideFormScrollBars "{ME}", "B"
          EZ_GetSize "{ME}",FW!, FH!, 2
          VScroll&=0
          HScroll&=0
          CW&=FW!
          CH&=FH!
          SW&=EZ_WO("SW")
          SH&=EZ_WO("SH")
          SF$=""

          IF W&<=CW& AND H&<=CH& THEN
               ' no scrollbars
               X&=(CW&-W&)\2
               Y&=(CH&-H&)\2
          ELSE
               EW&=0
               EH&=0
               IF W&>CW& THEN EH&=SH&
               IF H&>CH& THEN EW&=SW&
               IF W&>(CW&-EW&) THEN
                    X&=0
                    SF$=SF$+"H"
                    HScroll&=W&-(CW&-EW&)
               ELSE
                    X&=((CW&-EW&)-W&)/2
               END IF
               IF H&>(CH&-EH&) THEN
                    Y&=0
                    SF$=SF$+"V"
                    VScroll&=H&-(CH&-EH&)
               ELSE
                    Y&=((CH&-EH&)-H&)/2
               END IF
          END IF
          IF X&<0 THEN X&=0
          IF Y&<0 THEN Y&=0
          EZ_ResizeForm F$,EZ_CX(X&),EZ_CY(Y&), EZ_CX(W&),EZ_CY(H&), -1
          EZ_ShowFormScrollBars "{ME}", SF$
          EZ_ShowForm F$
          EZ_SetCmpText "{ME}",0, F$,1
          IF INSTR(SF$,"H") THEN
               EZ_SetHScroll "{ME}",0, 0, HScroll&, 0,1
          END IF
          IF INSTR(SF$,"V") THEN
               EZ_SetVScroll "{ME}",0, 0, VScroll&, 0,1
          END IF

          EZ_UpdateClient "{ME}",0
     END IF
END SUB

SUB PGScrollMe(BYVAL SMode&, BYVAL CVal&)
     LOCAL C!, R!, W!, H!, F$
     F$= EZ_GetCmpText("{ME}",0,1)
     IF F$="" THEN EXIT SUB
     IF EZ_Handle(F$,0)=0 THEN EXIT SUB
     EZ_GetPos F$, C!, R!,4
     IF SMode&=-1 THEN
          R!=0-EZ_CY(CVal&)
     ELSE
          C!=0-EZ_CX(CVal&)
     END IF
     EZ_MoveForm F$, C!, R!
END SUB
'<<END>>

SUB PGSCROLLER_Events(CID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CID&
          CASE %EZ_Window
               SELECT CASE CMsg&
                    CASE %EZ_Loading
                    CASE %EZ_Loaded
                         EZ_HideFormScrollBars "{ME}", "B"
                         ' No Page Forms to start with
                    CASE %EZ_CmpSet
                         LOCAL Cmd$, D$
                         EZ_CmpGetData Cmd$, D$
                         SELECT CASE Cmd$
                              CASE "SHOW"
                                   ' form must have been created as a child of this component
                                   CS_ShowForm D$
                              CASE ELSE
                         END SELECT
                    CASE %EZ_TextUpdated
                         SELECT CASE CVal&
                              CASE 1
                              CASE ELSE
                         END SELECT
                    CASE %EZ_BitmapUpdated
                    CASE %EZ_ColorUpdated
                         LOCAL FG&, BG&
                         FG&=EZ_GetCmpAttr("{ME}",0,1)
                         BG&=CVal&
                         EZ_SetColor "{ME}",0, FG&, BG&
                    CASE %EZ_FontUpdated
                    CASE %EZ_SelUpdated
                    CASE %EZ_ClearUpdated
                    CASE %EZ_FreeNow
                    CASE %EZ_Started
                    CASE %EZ_Close
                    CASE ELSE
               END SELECT
          CASE -1        ' Vertical scrollbar
               IF CMsg&=%EZ_Change THEN
                    PGScrollMe -1, CVal&
               END IF
          CASE -2        ' Horizontal scrollbar
               IF CMsg&=%EZ_Change THEN
                    PGScrollMe -2, CVal&
               END IF
          CASE ELSE
     END SELECT
END SUB



'<<END ALL FORMS>>    UnKnown Routines follow:
#IF %EZ_NOSKIPCODE
#ENDIF 'PARSE END
