/*****************/
/**             **/
/**  Constants  **/
/**             **/
/*****************/

#ifndef TRUE
#define	TRUE	1
#endif

#ifndef	FALSE
#define	FALSE	0
#endif




/*************/
/**         **/
/**  Types  **/
/**         **/
/*************/

typedef signed   int  BOOL;
typedef signed   char SBYTE;
typedef unsigned char UBYTE;
typedef signed   int  SWORD;
typedef unsigned int  UWORD;
typedef signed   long SLONG;
typedef unsigned long ULONG;

