
' *************************************************************************************
'                    Code Generated by EZGUI Professional Visual Designer 5.1
'           Portions: Copyright Christopher R. Boss, 2003 to 2012 All Rights Reserved !
'            Registered EZGUI 5.0 and 5.1 users may use generated code Royalty Free !
' *************************************************************************************
'
' -----------------------------------------------------------------------------------------
'            WARNING !    Do Not Modify any code WITHIN Protected Sections !
' You can add code (Sub,Function,etc.) BEFORE any Protected Routine by using the following
' CODE TAGS:        '<<SAVE>>      '<<END>>            and the Designer will not remove it.
' -----------------------------------------------------------------------------------------
'

' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================


'
'#COMPILE EXE
'#DIM ALL        '   This is helpful to prevent errors in coding

' --------------------
#INCLUDE "C:\ezgui50pro\includes\ezgui50.inc"                          ' EZGUI Include file for Declares
' --------------------
#RESOURCE ".\rcdata\graphicUI.pbr"

' *************************************************************************************


' *************************************************************************************
'                   Code Generator Defined Constants and Declares
' *************************************************************************************
DECLARE FUNCTION Main_Initialize(BYVAL VerNum&) AS LONG
DECLARE SUB OtherForm_Events(FormName$, CID&, CMsg&, CVal&, Cancel&)
DECLARE SUB OtherForm_Design(FormName$)
DECLARE FUNCTION PreProcess_Events(FormName$, CID&, CMsg&, CVal&, Cancel&) AS LONG
DECLARE SUB EZ_MAIN_Display(BYVAL FParent$)
DECLARE SUB EZ_MAIN_Design()
DECLARE SUB EZ_MAIN_ParseEvents(CID&, CMsg&, CVal&, Cancel&)
DECLARE SUB MAIN_Events(CID&, CMsg&, CVal&, Cancel&)
' ------------------------------------------------

%MAIN_LABEL1             = 100

DECLARE SUB EZ_FLOAT1_Display(BYVAL FParent$)
DECLARE SUB EZ_FLOAT1_Design()
DECLARE SUB EZ_FLOAT1_ParseEvents(CID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_Events(CID&, CMsg&, CVal&, Cancel&)
' ------------------------------------------------

%FLOAT1_BUTTON1            = 100
%FLOAT1_BUTTON2            = 105
%FLOAT1_BUTTON3            = 110
%FLOAT1_BUTTON4            = 115
%FLOAT1_BUTTON5            = 120
%FLOAT1_BUTTON6            = 125
%FLOAT1_BUTTON7            = 130
%FLOAT1_BUTTON8            = 135
%FLOAT1_BUTTON9            = 140
%FLOAT1_BUTTON10           = 145
%FLOAT1_BUTTON11           = 150
%FLOAT1_BUTTON12           = 155

DECLARE SUB FLOAT1_BUTTON1_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON2_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON3_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON4_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON5_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON6_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON7_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON8_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON9_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON10_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON11_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB FLOAT1_BUTTON12_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB EZ_KEDIT_Display(BYVAL FParent$)
DECLARE SUB EZ_KEDIT_Design()
DECLARE SUB EZ_KEDIT_ParseEvents(CID&, CMsg&, CVal&, Cancel&)
DECLARE SUB KEDIT_Events(CID&, CMsg&, CVal&, Cancel&)
' ------------------------------------------------

%KEDIT_TEXT1              = 100
%KEDIT_APPLYBUTTON        = 105
%KEDIT_CANCELBUTTON       = 110
%KEDIT_SHAPE1             = 115

DECLARE SUB KEDIT_TEXT1_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB KEDIT_APPLYBUTTON_Events(MyID&, CMsg&, CVal&, Cancel&)
DECLARE SUB KEDIT_CANCELBUTTON_Events(MyID&, CMsg&, CVal&, Cancel&)



' *************************************************************************************
'                 Code Generator Defined Global Variables and Types
' *************************************************************************************



'    Note:     Do NOT change the names of the EZGUI Callback Procedures !

' --------------------
#INCLUDE "C:\ezgui50pro\includes\ezwmain50.inc"                          ' EZGUI Include file for WinMain
' --------------------
DECLARE SUB InitAppScale()



' *************************************************************************************
'                       User Defined Global Variables and Types
'         (Put code in CODE TAGS! to protect from deletion by Code Generator !)
' *************************************************************************************


'<<SAVE>>
%EZ_MyUserID = 6071
%EZ_MyRegNumber = 570416930

%IntegrateCCApp =   1
#IF %IntegrateCCApp
#ELSE
    #INCLUDE "COMDLG32.INC"
    #INCLUDE "WIN32API.INC"
#ENDIF
'<<END>>

SUB EZ_Main(VerNum&)     ' (PROTECTED)
     EZ_Reg %EZ_MyUserID,%EZ_MyRegNumber
     InitAppScale
REM
' Help me
     EZ_DefImageFolder "Graphics"
     EZ_AllowCommandEvents  0
     EZ_AllowKeyEvents 2
     EZ_DefFont 6, "Arial Black", 10, " BV"
     EZ_DefFont 7, "Courier New", 10, "F"
     EZ_DefFont 8, "Times New Roman", 10, "V"
     EZ_DefFont 9, "Modern", 10, "V"
     EZ_DefSystemColor 32, 4
     EZ_DefSystemColor 33, 5
     EZ_DefSystemColor 34, 15
     EZ_DefSystemColor 35, 24
     EZ_DefColorL 36, &H001E1E1E
     EZ_DefColorL 37, &H0014AB9F
     EZ_DefColorL 38, &H0047A7FF
     EZ_DefColorL 39, &H00D2AACF
     EZ_DefColorL 40, &H001CD5E3
     EZ_DefColorL 41, &H00BC8943
     EZ_DefColorL 42, &H006C6AB7
     EZ_DefColorL 43, &H00DD4489
     IF Main_Initialize(VerNum&) THEN
          EZ_MAIN_Display ""
     END IF
END SUB

SUB InitAppScale()
     ' AutoScaling is default unless you call EZ_DefCharSizeA
END SUB



' -------------------------------------------------------------------------------------

SUB EZ_DesignWindow(FormName$)     ' (PROTECTED)
     SELECT CASE FormName$
          CASE "FLOAT1"
               EZ_FLOAT1_Design
          CASE "KEDIT"
               EZ_KEDIT_Design
          CASE ELSE
               OtherForm_Design FormName$
     END SELECT
END SUB

' -------------------------------------------------------------------------------------

SUB EZ_Events(FormName$, CID&, CMsg&, CVal&, Cancel&)     ' (PROTECTED)
     IF PreProcess_Events(FormName$, CID&, CMsg&, CVal&, Cancel&) THEN EXIT SUB
     SELECT CASE FormName$
          CASE "FLOAT1"
               EZ_FLOAT1_ParseEvents CID&, CMsg&, CVal&, Cancel&
          CASE "KEDIT"
               EZ_KEDIT_ParseEvents CID&, CMsg&, CVal&, Cancel&
          CASE ELSE
               OtherForm_Events FormName$, CID&, CMsg&, CVal&, Cancel&
     END SELECT
END SUB

' -------------------------------------------------------------------------------------





' *************************************************************************************
'                                Applications FORM Code
' *************************************************************************************


' ======================================
' [USER ACCESSABLE CODE]  You may Edit !
' ======================================

FUNCTION Main_Initialize(BYVAL VerNum&) AS LONG
     LOCAL RV&
     EZ_AllowCursorEvents 1
     EZ_AllowKeyEvents 1
     RV&=1
     FUNCTION=RV&
END FUNCTION

SUB OtherForm_Design(FormName$)
     SELECT CASE FormName$
          CASE ELSE
     END SELECT
END SUB

SUB OtherForm_Events(FormName$, CID&, CMsg&, CVal&, Cancel&)
     SELECT CASE FormName$
          CASE "{OPENDLG}", "{SAVEDLG}", "{OPENDLGX}", "{SAVEDLGX}", "{COLORDLG}", "{FONTDLG}", "{PRINTDLG}", "{PAGEDLG}", "{FINDDLG}"
          CASE "{ABORTDLG}"
          CASE "{MSGBOX}"
          CASE "{APP}"      ' Not a Form
               SELECT CASE CMsg&
                    CASE %EZ_NoTheme
                    CASE %EZ_Terminate
               END SELECT
          CASE ELSE
     END SELECT
END SUB

FUNCTION PreProcess_Events(FormName$, CID&, CMsg&, CVal&, Cancel&) AS LONG
     LOCAL RV&
     RV&=0
     FUNCTION=RV&
END FUNCTION


'<<BEGINFORM>> "MAIN"


' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================

SUB EZ_MAIN_Display(BYVAL FParent$)     ' (PROTECTED)
     EZ_Color 0, 36
     EZ_AllowLoadingEvent 2
     EZ_FormEx "MAIN", FParent$, "EPRI Calc 98 version 1.00", 0, 0, 150, 50, "^CHKZ", CODEPTR(EZ_MAIN_Design), CODEPTR(EZ_MAIN_ParseEvents)
END SUB

SUB EZ_MAIN_Design()     ' (PROTECTED)
     LOCAL CText$
     EZ_Color 12, 0
     EZ_UseIFont "Arial Black", 48,"BV"
     EZ_UseAutoSize "VH"
     EZ_Label %MAIN_LABEL1, 2, 19.75, 146.25, 9.125, "Loading Display !   Please wait.", "^CF"
     ' -----------------------------------------------
END SUB


SUB EZ_MAIN_ParseEvents(CID&, CMsg&, CVal&, Cancel&)     ' (PROTECTED)
     SELECT CASE CID&
          CASE %EZ_Window
               MAIN_Events CID&, CMsg&, CVal&, Cancel&
          CASE ELSE
               MAIN_Events CID&, CMsg&, CVal&, Cancel&
     END SELECT
END SUB

' ======================================
' [USER ACCESSABLE CODE]  You may Edit !
' ======================================
'<<SAVE>>
GLOBAL App_hGraphicWindow AS DWORD
%App_ShowFloat  =   1

SUB EZ_AttachGW(BYVAL hChild AS DWORD)
    SetParent hChild, EZ_Handle("MAIN",0)
    App_hGraphicWindow = hChild
    EZ_PostEvent "MAIN", 0, %App_ShowFloat
END SUB
'<<END>>

MACRO EZ_PBMAIN = EZ_PBMAINFUNC AS LONG
GLOBAL App_RunPlotDone&

SUB MAIN_Events(CID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CID&
          CASE %EZ_Window
               SELECT CASE CMsg&
                    CASE %EZ_NoAutoSize
                        Cancel&=1
                    CASE %EZ_Loading
                    CASE %EZ_Loaded
                    CASE %EZ_Started
                        LOCAL X&
                        EZ_MaximizeForm "MAIN"
                        App_RunPlotDone& = 0
                        #IF %IntegrateCCApp
                            X& = EZ_PBMAINFUNC()
                            EZ_UnloadForm "FLOAT1"
                        #ELSE
                            EZ_KEDIT_Display "Main"
                            EZ_FLOAT1_Display "Main"
                        #ENDIF
                        EZ_SetText "MAIN", %MAIN_LABEL1, "Display Ended!
                        App_RunPlotDone& = 1
                    CASE %EZ_Close
                        IF App_RunPlotDone& = 0 THEN
                            Cancel& =  -1
                        END IF
                    CASE %EZ_Post
                        IF CVal&=%App_ShowFloat THEN
                            EZ_FLOAT1_Display "MAIN"
                        END IF
                    CASE ELSE
               END SELECT
          CASE ELSE
     END SELECT
END SUB



'<<BEGINFORM>> "FLOAT1"


' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================

SUB EZ_FLOAT1_Display(BYVAL FParent$)     ' (PROTECTED)
     EZ_Color -1, -1
     EZ_AllowLoadingEvent 2
     EZ_Form "FLOAT1", FParent$, "Toolbar", 0, 0, 25, 13, "CHKST"
END SUB

SUB EZ_FLOAT1_Design()     ' (PROTECTED)
     LOCAL CText$
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON1, 1.25, .375, 22.5, 2.125, "Edit Azimuth Degree", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON1,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON2, 1.25, 2.75, 22.5, 2.125, "Edit Azimuth Radius", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON2,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON3, 1.25, 5.125, 22.5, 2.125, "Edit Circ Index Position", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON3,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON4, 1.25, 7.5, 22.5, 2.125, "Edit Axial Position", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON4,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON5, 1.5, 10.875, 10.5, 2.125, "dummy 5", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON5,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON6, 1.5, 13.375, 10.5, 2.125, "dummy 6", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON6,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON7, 1.5, 15.875, 10.5, 2.125, "dummy 7", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON7,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON8, 1.25, 18.125, 10.5, 2.125, "dummy 8", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON8,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON9, 13, 11, 10.5, 2.125, "dummy 9", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON9,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON10, 13.25, 13.375, 10.5, 2.125, "dummy 10", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON10,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON11, 12.75, 15.875, 10.5, 2.125, "dummy 11", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON11,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 25
     EZ_UseFont 6
     EZ_ODButton %FLOAT1_BUTTON12, 13, 18.375, 10.5, 2.125, "dummy 12", "T"
     EZ_SetRegion "FLOAT1", %FLOAT1_BUTTON12,-2,0
     ' -----------------------------------------------
END SUB


SUB EZ_FLOAT1_ParseEvents(CID&, CMsg&, CVal&, Cancel&)     ' (PROTECTED)
     SELECT CASE CID&
          CASE %EZ_Window
               FLOAT1_Events CID&, CMsg&, CVal&, Cancel&
          CASE  %FLOAT1_BUTTON1
               FLOAT1_BUTTON1_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON1, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON2
               FLOAT1_BUTTON2_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON2, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON3
               FLOAT1_BUTTON3_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON3, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON4
               FLOAT1_BUTTON4_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON4, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON5
               FLOAT1_BUTTON5_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON5, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON6
               FLOAT1_BUTTON6_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON6, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON7
               FLOAT1_BUTTON7_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON7, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON8
               FLOAT1_BUTTON8_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON8, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON9
               FLOAT1_BUTTON9_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON9, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON10
               FLOAT1_BUTTON10_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON10, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON11
               FLOAT1_BUTTON11_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON11, CVal&, 25, 0,  6
               END IF
          CASE  %FLOAT1_BUTTON12
               FLOAT1_BUTTON12_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "FLOAT1", %FLOAT1_BUTTON12, CVal&, 25, 0,  6
               END IF
          CASE ELSE
               FLOAT1_Events CID&, CMsg&, CVal&, Cancel&
     END SELECT
END SUB

' ======================================
' [USER ACCESSABLE CODE]  You may Edit !
' ======================================
'<<SAVE>>
SUB EZ_PositionFloats()

    LOCAL hWnd AS LONG, XOffset!, YOffset!
    DIM P(1 TO 4) AS LONG
    #IF %IntegrateCCApp
        hWnd = App_hGraphicWindow
    #ELSE
        hWnd = EZ_Handle("MAIN",0)
    #ENDIF
    GetWindowRect hWnd, BYVAL VARPTR(P(1))
    XOffset! = 2
    YOffset! = 48
    EZ_MoveForm "FLOAT1", EZ_CX(P(2))+XOffset!, EZ_CY(P(1))+YOffset!
END SUB

SUB EZ_ResetFocus()
    DIM P(1 TO 2) AS INTEGER
    P(1)=0
    P(2)=0
    SendMessage App_hGraphicWindow, %WM_NCLBUTTONDOWN, %HTCAPTION, BYVAL VARPTR(P(1))
    SendMessage App_hGraphicWindow, %WM_NCLBUTTONUP, %HTCAPTION, BYVAL VARPTR(P(1))
END SUB

GLOBAL App_FakeKey$

SUB EZ_AddKey(BYVAL T$)
    App_FakeKey$=App_FakeKey$+T$
END SUB

SUB EZ_CheckEvents()
    EZ_DoEvents 5
END SUB

FUNCTION EZ_GraphicInstat() AS LONG
    LOCAL RV&
    RV&=0
    GRAPHIC INSTAT TO RV&
    IF RV&=0 THEN
        IF LEN(App_FakeKey$)<>0 THEN RV&=1
    END IF
    FUNCTION=RV&
END FUNCTION

FUNCTION EZ_GraphicInkey$()
    LOCAL RV$
    RV$=""
    GRAPHIC INKEY$ TO RV$
    IF RV$="" THEN  ' test for EZGUI controls as fake keys
        IF LEN(App_FakeKey$)<>0 THEN
            IF ASC(MID$(App_FakeKey$,1,1))=0 THEN
                ' two codes
                RV$=MID$(App_FakeKey$,1,2)
                App_FakeKey$=MID$(App_FakeKey$,3)
            ELSE
                ' one code
                RV$=MID$(App_FakeKey$,1,1)
                App_FakeKey$=MID$(App_FakeKey$,2)
            END IF
        END IF
    END IF
    FUNCTION=RV$
END FUNCTION
'<<END>>

SUB FLOAT1_Events(CID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CID&
          CASE %EZ_Window
               SELECT CASE CMsg&
                    CASE %EZ_SelectCursor
                        EZ_SetCursor "", 0
                        Cancel&=1
                    CASE %EZ_Loading

                    CASE %EZ_Loaded
                    CASE %EZ_Started
                        EZ_PositionFloats
                        EZ_ShowForm "FLOAT1"
                    CASE %EZ_Close
                    CASE ELSE
               END SELECT
          CASE ELSE

     END SELECT
END SUB

SUB FLOAT1_BUTTON1_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_SelectCursor
             EZ_SetCursor "", 0
             Cancel&=1
          CASE %EZ_Click
             EZ_AddKey "Z"
'             EZ_PostEvent "{ME}", MyID&, 1
          CASE %EZ_Post
'              EZ_ResetFocus
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON2_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_SelectCursor
             EZ_SetCursor "", 0
             Cancel&=1
          CASE %EZ_Click
             EZ_AddKey "R"
'             EZ_PostEvent "{ME}", MyID&, 1
          CASE %EZ_Post
'              EZ_ResetFocus
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON3_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_SelectCursor
             EZ_SetCursor "", 0
             Cancel&=1
          CASE %EZ_Click
             EZ_AddKey "C"
'             EZ_PostEvent "{ME}", MyID&, 1
          CASE %EZ_Post
'              EZ_ResetFocus
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON4_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_SelectCursor
             EZ_SetCursor "", 0
             Cancel&=1
          CASE %EZ_Click
             EZ_AddKey "A"
'             EZ_PostEvent "{ME}", MyID&, 1
          CASE %EZ_Post
'              EZ_ResetFocus
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON5_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON6_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON7_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON8_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON9_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON10_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON11_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE ELSE
     END SELECT
END SUB

SUB FLOAT1_BUTTON12_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE ELSE
     END SELECT
END SUB



'<<BEGINFORM>> "KEDIT"


' ======================================
' [PROTECTED CODE]         Do NOT Edit !
' ======================================


'<<SAVE>>
GLOBAL App_Prompt AS STRING
GLOBAL App_Edit AS STRING
GLOBAL App_ExitCode AS LONG
GLOBAL App_TMask AS STRING

SUB EZ_KEdit (Prompt AS STRING, Edit AS STRING, ExitCode AS LONG, TMask AS STRING)
    App_Prompt = Prompt
    App_Edit = Edit
    App_ExitCode = ExitCode
    App_TMask = TMask
    EZ_KEDIT_Display "FLOAT1"
    Edit = TRIM$(App_Edit)
    ExitCode = App_ExitCode
END SUB

'<<END>>

SUB EZ_KEDIT_Display(BYVAL FParent$)     ' (PROTECTED)
     EZ_Color 0, 8
     EZ_AllowLoadingEvent 2
     EZ_Form "KEDIT", FParent$, "Enter Input", 0, 0, 56, 5, "CMST"
END SUB

SUB EZ_KEDIT_Design()     ' (PROTECTED)
     LOCAL CText$
     EZ_Color-1,-1
     EZ_UseIFont "Courier New", 14,"BF"
     EZ_AllowLoadingEvent 2
     EZ_Text %KEDIT_TEXT1, 3, 1.75, 21.5, 1.625, "9999999999", "EST"
     ' -----------------------------------------------
     EZ_Color 0, 10
     EZ_UseFont 6
     EZ_ODButton %KEDIT_APPLYBUTTON, 26.5, 1.125, 16.25, 2.75, "Apply", "T"
     EZ_SetRegion "KEDIT", %KEDIT_APPLYBUTTON,-2,0
     ' -----------------------------------------------
     EZ_Color 0, 20
     EZ_UseFont 6
     EZ_ODButton %KEDIT_CANCELBUTTON, 44.25, 1.125, 9.5, 2.75, "Cancel", "T"
     EZ_SetRegion "KEDIT", %KEDIT_CANCELBUTTON,-2,0
     ' -----------------------------------------------
     EZ_Color 9, 15
     EZ_UseFont 4
     EZ_Shape %KEDIT_SHAPE1, 0, 0, 56, 5, "", "4I["
     ' -----------------------------------------------
END SUB


SUB EZ_KEDIT_ParseEvents(CID&, CMsg&, CVal&, Cancel&)     ' (PROTECTED)
     SELECT CASE CID&
          CASE %EZ_Window
               KEDIT_Events CID&, CMsg&, CVal&, Cancel&
          CASE  %KEDIT_TEXT1
               KEDIT_TEXT1_Events CID&, CMsg&, CVal&, Cancel&
          CASE  %KEDIT_APPLYBUTTON
               KEDIT_APPLYBUTTON_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "KEDIT", %KEDIT_APPLYBUTTON, CVal&, 10, 0,  6
               END IF
          CASE  %KEDIT_CANCELBUTTON
               KEDIT_CANCELBUTTON_Events CID&, CMsg&, CVal&, Cancel&
               IF CMsg&=%EZ_OwnerDraw THEN
                    EZ_Draw3DButtonRR "KEDIT", %KEDIT_CANCELBUTTON, CVal&, 20, 0,  6
               END IF
          CASE ELSE
               KEDIT_Events CID&, CMsg&, CVal&, Cancel&
     END SELECT
END SUB

' ======================================
' [USER ACCESSABLE CODE]  You may Edit !
' ======================================

SUB KEDIT_Events(CID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CID&
          CASE %EZ_Window
               SELECT CASE CMsg&
                    CASE %EZ_Loading
                        EZ_SetLoadStr "T", App_Prompt
                    CASE %EZ_Loaded
                    CASE %EZ_Started
                    CASE %EZ_Close
                        EZ_PostEvent "{ME}", 0, 1
                    CASE %EZ_Post
                        EZ_ResetFocus
                    CASE ELSE
               END SELECT
          CASE ELSE
     END SELECT
END SUB

SUB KEDIT_TEXT1_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Loading
              IF App_TMask<>"" THEN
                 IF LEN(App_Edit)=LEN(App_TMask) THEN
'                     EZ_SetLoadStr "P", "EST"+"{"+App_TMask+"}"
                 END IF
              END IF
              EZ_SetLoadStr "T", App_Edit
          CASE %EZ_Change
          CASE ELSE
     END SELECT
END SUB

SUB KEDIT_APPLYBUTTON_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
              App_Edit = EZ_GetText("KEDIT", %KEDIT_TEXT1)
              App_ExitCode = 13
              EZ_UnloadForm "{ME}"
          CASE ELSE
     END SELECT
END SUB

SUB KEDIT_CANCELBUTTON_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
             App_ExitCode = 27
              EZ_UnloadForm "{ME}"
          CASE ELSE
     END SELECT
END SUB



'<<END ALL FORMS>>    UnKnown Routines follow:
#IF %EZ_NOSKIPCODE
SUB MAIN_BUTTON1_Events( MyID&, CMsg&, CVal&, Cancel&)
     SELECT CASE CMsg&
          CASE %EZ_Click
          CASE ELSE
     END SELECT
END SUB
#ENDIF 'PARSE END
